from typing import Any
from PIL.Image import Image

class PdfiumBitmap:
    def to_pil(self) -> Image: ...

class PdfPage:
    def render(
        self,
        scale: float = ...,
        rotation: int = ...,
        crop: tuple[int, int, int, int] = ...,
        **kwargs: Any
    ) -> PdfiumBitmap: ...
    def close(self) -> None: ...

class PdfDocument:
    def __init__(self, input: str | bytes | None = ..., **kwargs: Any) -> None: ...
    def __len__(self) -> int: ...
    def get_page(self, index: int) -> PdfPage: ...
    def close(self) -> None: ...
