from typing import Any
import numpy as np
from numpy import ndarray

def Canny(image: ndarray[Any, Any], threshold1: float, threshold2: float, **kwargs: Any) -> ndarray[Any, Any]: ...
def HoughLines(image: ndarray[Any, Any], rho: float, theta: float, threshold: int, **kwargs: Any) -> ndarray[Any, Any] | None: ...
